### Exercícios Sobre Módulos Python Para Análise de Dados

### Exercício 1

In [3]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

import numpy as np

arrayNP = np.array(range(0,1000000))
lista = list(np.array(range(0,1000000)))

%timeit arrayNP * 2

%timeit [x*2 for x in lista]

1.41 ms ± 3.91 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
184 ms ± 1.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Exercício 2

In [55]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

import numpy as np

vetor = np.array([15,20,45,82,1,2,56,87,78,10])

In [60]:
vetor[5:8] = 0
vetor

array([15, 20, 45, 82,  1,  0,  0,  0, 78, 10])

### Exercício 3

In [2]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

import numpy as np

array3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array3[[0]]

array([[1, 2, 3]])

### Exercício 4

In [38]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

import numpy as np

matriz = np.array([[1,2,3,4],[5,6,7,8],[0,0,0,0],[9,9,9,9]])
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 0, 0, 0],
       [9, 9, 9, 9]])

In [34]:
# Imprima os elementos da terceira linha da matriz
matriz[2]

array([0, 0, 0, 0])

In [35]:
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
matriz[0:2, 1:3]

array([[2, 3],
       [6, 7]])

### Exercício 5

In [10]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
list(zip(*arr))

[(0, 5, 10), (1, 6, 11), (2, 7, 12), (3, 8, 13), (4, 9, 14)]

In [13]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [92]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [95]:
for c,x,y in zip(cond,xarr,yarr):
    if c == True:
        print(x)
    else:
        print(y)
        

1.1
2.2
1.3
1.4
2.5


### Exercício 7

In [97]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

A = np.array([0,1,2,3,4,5,6,7,8,9])
arquivo = open('save.npy', 'w')
arquivo.write(str(A))
arquivo.close()

In [102]:
arquivo = open('save.npy', 'r')
B = arquivo.read()
arquivo.close()
np.array(B)

array('[0 1 2 3 4 5 6 7 8 9]', dtype='<U21')

### Exercício 8

In [14]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b','h'])

In [15]:
obj.unique()

array(['c', 'a', 'd', 'b', 'h'], dtype=object)

### Exercício 9

In [122]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [123]:
import pandas as pd

resultado = pd.DataFrame(resp.json(), columns=['number', 'title', 'labels','state'])
resultado

number                                              title  \
0    25895  Implement helper method to get char* buffer fr...   
1    25894                    Skipped flaky part of test_time   
2    25893  Memory leak with .rolling().max() in pandas 0....   
3    25892  GroupBy.apply repeats the first group N times ...   
4    25891  MultiIndex level dropped when multiplying two ...   
5    25888  Pass the errors and kwargs arguments through t...   
6    25887                           Empty dataframe creation   
7    25886          CLN: Remove PY2/3 references io directory   
8    25884                       Initial pandas.typing Module   
9    25883  Performance regression in 0.24+ on DataFrame B...   
10   25882          Typing Cleanup - Remove Blacklisted Items   
11   25881       .at does not work using a categorical index.   
12   25880  Int64Dtype conversion seems to casts to double...   
13   25877  Unexpected behaviour of groupby.apply with Dat...   
14   25875                       test_time failure in CI logs   
15   25873  CLN: Remove miscellaneous rarely used items fr...   
16   25871  groupby aggregation on ordered Categorial with...   
17   25863                      Read hdf does not close store   
18   25860  [BUG] IntervalIndex.get_loc error for decreasi...   
19   25858  Styler.applymap(subset=...) breaks promise tha...   
20   25857  expanding(min_periods=N).count(), for any N, r...   
21   25853  BUG: Fix Timestamp type checks to work with su...   
22   25851  Fix PyDateTime_CheckExact checks as proxy for ...   
23   25848  read_csv : using day first 23x to 35x slower t...   
24   25846                 reset_index() error after crosstab   
25   25843  DataFrame (and Series?) constructor ignores re...   
26   25839  df.to_hdf5() in table append mode very slow wi...   
27   25838  ENH: keep='random' option for .duplicated and ...   
28   25837  to_msgpack converts tuples of length 1 to str ...   
29   25833  RecursionError with self referencing column in...   

                                               labels state  
0                                                  []  open  
1   [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
2   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
3                                                  []  open  
4                                                  []  open  
5   [{'id': 1049312478, 'node_id': 'MDU6TGFiZWwxMD...  open  
6   [{'id': 1049312478, 'node_id': 'MDU6TGFiZWwxMD...  open  
7   [{'id': 49747336, 'node_id': 'MDU6TGFiZWw0OTc0...  open  
8   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
9   [{'id': 1049312478, 'node_id': 'MDU6TGFiZWwxMD...  open  
10  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
11                                                 []  open  
12                                                 []  open  
13                                                 []  open  
14  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
15  [{'id': 49747336, 'node_id': 'MDU6TGFiZWw0OTc0...  open  
16  [{'id': 40153326, 'node_id': 'MDU6TGFiZWw0MDE1...  open  
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
18  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
19                                                 []  open  
20  [{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5...  open  
21  [{'id': 49094459, 'node_id': 'MDU6TGFiZWw0OTA5...  open  
22  [{'id': 49094459, 'node_id': 'MDU6TGFiZWw0OTA5...  open  
23  [{'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIy...  open  
24  [{'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc...  open  
25  [{'id': 1049312478, 'node_id': 'MDU6TGFiZWwxMD...  open  
26                                                 []  open  
27                                                 []  open  
28                                                 []  open  
29                                                 []  open

### Exercício 10

In [19]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

import sqlite3

# Criando o Banco de Dados
conn = sqlite3.connect('data\exercicio10.db')

# Definindo um cursor
cursor = conn.cursor()

# Criando uma tabela (schema)
cursor.execute("""
CREATE TABLE Pessoa (
            id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
            nome TEXT NOT NULL,
            idade INTEGER
);
""")
print("Tabela criada com sucesso!")

Tabela criada com sucesso!


In [21]:
# Inserindo alguns registros
lista = [
    ('Aline', 36),
    ('Stefano', 32),
    ('Larissa', 6),
    ('Hugo', 4),
    ('Evelyn', 13),
    ('Cynthia', 35),
    ('Esther', 6),
    ('Arthur', 8)
]


cursor.executemany("""
INSERT INTO Pessoa (nome, idade)
VALUES (?, ?)
""", lista)

# gravando no banco de dados
conn.commit()

print('Dados inseridos com sucesso.')

Dados inseridos com sucesso.


In [38]:
# Consultando os dados
listaPessoa = cursor.execute("""
SELECT * FROM Pessoa
""")

listaPessoa = list(listaPessoa)

In [42]:
# retornando os dados com o pandas

import pandas as pd
pd.DataFrame(listaPessoa, columns=['id', 'Nome', 'Idade'])

id     Nome  Idade
0   1    Aline     36
1   2  Stefano     32
2   3  Larissa      6
3   4     Hugo      4
4   5   Evelyn     13
5   6  Cynthia     35
6   7   Esther      6
7   8   Arthur      8

In [45]:
# Alterando os dados
id_pessoa = 1
nova_idade = 40

cursor.execute("""
    UPDATE Pessoa
    SET idade = ?
    WHERE id = ?
""", (nova_idade, id_pessoa))

conn.commit()

# Verificando a informação alterada
listaPessoa1 = cursor.execute("""
SELECT * FROM Pessoa
""")

pd.DataFrame(list(listaPessoa1), columns=['id', 'Nome', 'Idade'])

id     Nome  Idade
0   1    Aline     40
1   2  Stefano     32
2   3  Larissa      6
3   4     Hugo      4
4   5   Evelyn     13
5   6  Cynthia     35
6   7   Esther      6
7   8   Arthur      8

In [46]:
# Fechando a conexão
conn.close()